name: Build API container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build image
      run: docker build . --file Dockerfile --tag nfi-daniel:$(date +%s) --tag nfi-daniel:latest
#    - name: Upload image
#      run: docker image push --all-tags